Add German Translation
NerdHubMC/Refined-Machinery pull request #39
Opened 2019-06-02 19:37 UTC by pandory-network

2019-06-04 08:04 UTC, UpcraftLP requested changes

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.lead_dust" : "Leadstaub",
Lead -> Blei

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.lead_ingot" : "Leadbarren",
Lead -> Blei

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.diamond_dust" : "Diamandstaub",
Diaman`t`, not Diaman`d`

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.energized_steel_ingot" : "Energie Stahlbarren",
it's not an "energy steel ingot"

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.energized_sword" : "Energie Schwert",
energy != energized

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.linker" : "Linker Tool",
`Verbindungswerkzeug`

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.wrench": "Utility Wrench",
`Schraubenschlüssel`

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.robotic_wings": "Robo Flügel",
Robo`-`Flügel

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "item.refinedmachinery.block_exchanger": "Block Exchanger",
this name is not translated at all

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.lead_block" : "Lead Block",
Lead -> Blei

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.lead_ore" : "Lead Ore",
this name is not translated at all

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.nickel_ore" : "Nickel Ore",
this name is not translated at all

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.nickel_block" : "Nickel Block",
should be combined into one word

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.silver_block" : "Silber Block",
should be combined into one word

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.silver_ore" : "Silber Ore",
`ore`?

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.tin_block" : "Zinn Block",
should be combined into one word

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.tin_ore" : "Zinn Ore",
`ore`?

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.energy_furnace" : "Energie Ofen",
maybe find a better translation

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.quarry" : "Quarry",
needs translation

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.wireless_controller" : "Wireless Energy Controller",
needs translation

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.wireless_transmitter" : "Wireless Energy Transmitter",
needs translation

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.lava_generator" : "Lava Generator",
`Lava-Generator`

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.energy_charger" : "Energy Ladegerät",
drop the `energy` prefix

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.fluid_pump" : "Flüssigkeitspumpe",
jusst `Pumpe` would do

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.farmer" : "Farmer Block",
-> `Ernter`, and no `block` suffix

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.mob_grinder" : "Mob Grinder",
translation?

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.vacuum" : "Vacuum Block",
needs translation

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.energy_cell" : "Kardinal Energiezelle",
`Cardinal Energy` is the energy unit, not part of the item name

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.machine_frame" : "Machinenrahmen",
Ma`s`chine

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.energy_cable" : "Energy Transfer Kabel",
just `Kabel` or `Energiekabel`

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.coalgen" : "Kohle Generator",
`Kohle-Generator`

2019-06-04 08:04 UTC, UpcraftLP commented on src/main/resources/assets/refinedmachinery/lang/de_de.json
> +  "block.refinedmachinery.disenchanter" : "Disenchanter"
needs translation

2019-06-15 07:53 UTC, kaffeekirsche reviewed
Fix Translation

2019-06-15 20:16 UTC, UpcraftLP approved these changes

2019-08-02 17:38 UTC, merged